<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions targetNamespace="http://uniboard.bfh.ch/" name="UniBoardService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:tns="http://uniboard.bfh.ch/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://uniboard.bfh.ch/" schemaLocation="UniBoardService_schema1.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://uniboard.bfh.ch/data" schemaLocation="UniBoardService_schema2.xsd"/>
		</xsd:schema>
	</types>
	<message name="get">
		<part name="parameters" element="tns:get"/>
	</message>
	<message name="getResponse">
		<part name="parameters" element="tns:getResponse"/>
	</message>
	<message name="post">
		<part name="parameters" element="tns:post"/>
	</message>
	<message name="postResponse">
		<part name="parameters" element="tns:postResponse"/>
	</message>
	<portType name="UniBoardService">
		<operation name="get">
			<input message="tns:get"/>
			<output message="tns:getResponse"/>
		</operation>
		<operation name="post">
			<input message="tns:post"/>
			<output message="tns:postResponse"/>
		</operation>
	</portType>
	<binding name="UniBoardServicePortBinding" type="tns:UniBoardService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<operation name="get">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
		<operation name="post">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="UniBoardService">
		<port name="UniBoardServicePort" binding="tns:UniBoardServicePortBinding">
			<soap:address location="REPLACE_WITH_ACTUAL_URL"/>
		</port>
	</service>
</definitions>

